data:
  corpus: 'DEMAND'
  root_path: 'data/'
  log_path: 'logs'
  data_type: 'train'
  sample_rate: 16000
  window_size: 16384
  window_stride: 0.5
  window: 'hamming'

hparas:
  batch_size: 64
  epochs: 1000
  optim:
    learning_rate: 0.0002
    betas: [0.9, 0.999]
    eps: 0.00000001
    weight_decay: 0
    amsgrad: False
  train_continue: False
  multi_gpu: False
  select_gpu: [0, 1]
  num_workers: 8
  checkpoint: 'model save name'
  save_path: 'model save path'
  log_path: 'logs save path'

test:
  model_path: 'model read path'
  file_path: 'test data path'
  result_save_path: 'result save path'
